version: '3'

services:
  server-test-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        allowedOrigins: "['127.0.0.1']"
        port: 4444
        host: "0.0.0.0"
        workdir: /usr/src/test
    ports:
      - "4444:4444"
