version: '3'

services:
  server-test-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        allowedOrigins: "[]"
        appPort: 4444
        exposePort: 4444
        host: "0.0.0.0"
        workdir: /usr/src/test
    ports:
      - "4444:4444"
